language: node_js
node_js:
- node
script: npm run test:coverage
deploy:
  provider: npm
  email: "masruizkevin@gmail.com"
  api_key:
    secure: nT+6H0lpk5EC5dl02vSN2Ke4weJimPtHP3La6HgN6OH5MvWxthaZvZouxCqB6mwlGASJvRJoQie/dxIOds1q+64loG+x72VI+Hi7VGG3SOnNM5E4AoZs0sZ960zJPZFPHhT7NxuPe/U5o6gjRF+mlfsY5fet60MNRFjJvADfT8z8ETjGt96hjHrvVBQ5b/G30HF6VbrAcDIn9NTg4BNy3LihBRDhdTUD8Wy4OmQMPyGOsFDHJvjT11r4y+Ah7oQBB3ZMkEDTergdyCssFBOGSxUaSzr1k74p7Qkdj8GB4J/TKYxH9F/+C5qnHSdQ5PeUTF5HO7dya5EKHu8L/iQqRZ8fHLu1OMs7+WxBfrlcBlYXhhLmlw6THxfqdkq6GZWA9RQOePT6D8RZ3qGX35PZKJo1XIRwS7clWQ8aQjK78Af5BK5qapuwTDvjBm2meK7ZmQ5GRZbwSOMsXSez5Ke9H76wcpTdXanLnfxr07TqKbj8JefOow1fRq0BQigvjRqX/LFJcrttZBJmJvX5GTqx0YsTesm826NXpayuykDH2UJDfYirVFtK7cwU/INk/ZgRWPyuIJZdYlc35R/04nMNWLqtqCyob8oC6Ob64V3ulnxb51TRp3w2qoXF/ZRkksezCcCRHHlibQ2MOArnmnj4B6UWzrxzDmorgs64T6i1ngc=
  on:
      tags: true